site_name: Projet Mosar | FNSO
site_description: Modèle ouvert de soutien et d’accompagnement des revues
site_url: https://nicocoquet.github.io/mosar/

nav:
  - Home: index.md
  - Partners: partenaires.md
  - Statistics: statistiques.md

theme:
  name: material
  language: fr
  logo: assets/logos/mosar.svg
  favicon: assets/icons/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Passer au mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Passer au mode clair

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: fr
          default: true
          name: Français
          build: true
          nav_translations:
            Home: Accueil
            Partners: Partenaires
            Statistics: Statistiques
        - locale: en
          name: English
          build: true

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      base_path:
        - .

extra_css:
  - stylesheets/extra.css

copyright: "Mosar | FNSO"
